version: "3"
services:
  TerraSLAM:
    image: orb-slam3-humble:22.04
    volumes:
      #full dev
      - /dev:/dev:rw
      #full media
      - /media:/media:rw
      #Time
      - /etc/timezone:/etc/timezone:rw
      - /etc/localtime:/etc/localtime:rw
      #ros-workspaces
      - ./container_root/:/root/
      - ./orb_slam3_ros2_wrapper/:/root/colcon_ws/src/orb_slam3_ros2_wrapper/
      - ./slam_msgs/:/root/colcon_ws/src/slam_msgs/
      # - ./ORB_SLAM3/:/home/orb/ORB_SLAM3/
      # X11 forwarding
      - ${XAUTHORITY}:/tmp/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/tmp/.Xauthority
      - QT_X11_NO_MITSHM=1
    entrypoint: ""
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        source /root/colcon_ws/install/setup.bash &&
        cd /root &&
        python3 server.py
      "
    ports:
      - "11223:22"
      - "5000:5000"
      - "9090:9090"
    container_name: TerraSLAM
